# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6530edac278434d3a6f9aaa87dc9fa1a553cffdd50c74396bc97f95813b8c5da7a8a6020b79d51e1467c982676405ea4571ac318026c5076bb8d21fc2dfe77b5

test:
  secret_key_base: 7120376a5adfb2f3d37042008644e67fbe9e2f9020a18fe8b6cffa8a3bfe295aa8480ef5af1817c2faf81be8fdab64861cf31a08d91f9486a6a31b3abcb510b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
